### ISSUE TITLE
找不到crashpad库

### ISSUE THREAD

**Issue by xinsuinizhuan** [RealChuan/Qt-App#3]
![图片](https://github.com/RealChuan/Qt-App/assets/40679769/4a2c0d89-748f-49c5-bdae-ab4deff8f01d)

..\..\..\..\src\dump\crashpad.cc(3): fatal error C1083: 无法打开包括文件: “crashpad/client/crash_report_database.h”: No such file or directory
..\..\..\..\src\dump\breakpad.cc(9): fatal error C1083: 无法打开包括文件: “client/windows/handler/exception_handler.h”: No such file or

**Comment by RealChuan** [comment]
vcpkg

提问前，先看看readme；
编译问题，先看看actions是怎么编译通过的；
